//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetoDichka_Work_with_image
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int id { get; set; }
        public string path { get; set; }

        public object Clone()
        {
            return new Images
            {
                id = id,
                path = path,
            };
        }
    }
}
